# Generated by Django 5.2.1 on 2025-08-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_cep_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF', max_length=11, null=True, verbose_name='cpf'),
        ),
    ]
