# Generated by Django 5.2.1 on 2025-08-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP', max_length=8, null=True, verbose_name='cep'),
        ),
    ]
