# Generated by Django 5.2.1 on 2025-08-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
