# Generated by Django 5.2.1 on 2025-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produto_categoria_alter_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
