# Generated by Django 5.2.5 on 2025-09-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
