# Generated by Django 5.2.5 on 2025-09-09 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_user_passage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='endereco',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='telefones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passage_id',
            field=models.CharField(default='', help_text='Passage ID', max_length=255, verbose_name='passage_id'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
