# Generated by Django 5.2.5 on 2025-11-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_carrinho_itenscarrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itenscarrinho',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.DeleteModel(
            name='ItensCarrinho',
        ),
    ]
